name: Build rust libmovevm
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "release/*"
    paths:
      - "crates/**"
      - '!crates/e2e-move-tests/**'
      - "libmovevm/**"
      - "libcompiler/**"
      - "Cargo.toml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux-glibc:
    name: Linux glibc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: make release-build-linux

      - uses: actions/upload-artifact@v3
        with:
          name: libmovevm-linux-glibc
          path: api/*.so

  build-macos:
    name: MacOS glibc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: make release-build-macos

      - uses: actions/upload-artifact@v3
        with:
          name: libmovevm-macos
          path: api/*.dylib

  commit:
    name: Commit shared libraries
    if: ${{ !startsWith(github.ref, 'refs/tags/') }} # Build linux-muslc only on tags/releases
    needs: [build-linux-glibc, build-macos]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
      - name: Get linux-glibc artifacts
        uses: actions/download-artifact@v3
        with:
          name: libmovevm-linux-glibc
          path: api

      - name: Get macos artifacts
        uses: actions/download-artifact@v3
        with:
          name: libmovevm-macos
          path: api

      - name: Commit shared libraries
        uses: EndBug/add-and-commit@v9
        with:
          add: '["api/libmovevm.dylib", "api/libmovevm.aarch64.so", "api/libmovevm.x86_64.so", "api/libcompiler.dylib", "api/libcompiler.aarch64.so", "api/libcompiler.x86_64.so"]'
          default_author: github_actions
          message: "update shared libraries"
